### ISSUE TITLE
找不到tp_data.cpp和tp_points_generate.cpp

### ISSUE THREAD

**Issue by Phoebe731178** [DAVAR-Lab/OCR#1]
Installiation时运行bash tp_setup.sh报错，好像没有对应的文件？

**Comment by icedream2** [comment]
你好，当前仓库已经迁移到https://github.com/hikopensource/DAVAR-Lab-OCR，在那个下面有

**Comment by Phoebe731178** [comment]
您好，我对您实现的text_perceptron这篇论文的代码的研究很感兴趣，但是自己复现的时候遇到了一点问题，请问能有什么方式可以跟您更方便的联系一下呀，想请教一些问题～



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月26日(周五) 中午11:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [DAVAR-Lab/OCR] 找不到tp_data.cpp和tp_points_generate.cpp (#1)




 
你好，当前仓库已经迁移到https://github.com/hikopensource/DAVAR-Lab-OCR，在那个下面有

**Comment by icedream2** [comment]
> 您好，我对您实现的text_perceptron这篇论文的代码的研究很感兴趣，但是自己复现的时候遇到了一点问题，请问能有什么方式可以跟您更方便的联系一下呀，想请教一些问题～
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年3月26日(周五) 中午11:06 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [DAVAR-Lab/OCR] 找不到tp_data.cpp和tp_points_generate.cpp (#1) 你好，当前仓库已经迁移到[https://github.com/hikopensource/DAVAR-Lab-OCR，在那个下面有](https://github.com/hikopensource/DAVAR-Lab-OCR%EF%BC%8C%E5%9C%A8%E9%82%A3%E4%B8%AA%E4%B8%8B%E9%9D%A2%E6%9C%89) — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by icedream2** [comment]
任何问题欢迎到新的代码仓库下的issue提出，或者可直接通过邮件发送至qiaoliang6@hikvision.com，我们会在第一时间进行解答
